[package]
name = "terr_3d"
version = "0.1.0"
authors = ["shockham <samuel.hockham@gmail.com>"]

[dependencies]
caper = { git = "https://github.com/shockham/caper" }
simdnoise = "3.0"
lazy_static = "1.0"
rayon = "1.0"
